### ISSUE TITLE
SYNOPSIS on MetaCPAN is incorrect

### ISSUE THREAD

**Issue by kevbo-oh** [nmelnick/Domain-PublicSuffix#6]
The SYNOPSIS section at the top of the MetaCPAN page says this:

my $tld = $suffix->tld();
# $tld now contains co.uk

That is incorrect.  tld is uk.  suffix is co.uk.

This threw me for a loop for a while until I read the later documentation that is correct.  (I even updated my installation, thinking that I'd found a bug in the 0.14 version I had been using.)

**Comment by nmelnick** [comment]
Ooof -- thanks for the heads up, I'll get that corrected for the next version.

**Comment by kevbo-oh** [comment]
Obviously, that comes from the pod.  Just noticed it is there when you do a perldoc.  Probably obvious to you.  Thanks!

**Comment by nmelnick** [comment]
This took forever, but this is fixed in 0.17.
